### ISSUE TITLE
Show checkboxes for all DPs in target detail view

### ISSUE THREAD

**Issue by joesingo** [joesingo/tom_education#21]
In the data product table in the target detail view, checkboxes should appear for *all* data products, not just FITS ones (as is the case currently).

Need to think about whether we need a new 'Select FITS' button to replace the existing use for 'Select All' (which is to run timelapse/pipeline on all FITS products).

**Comment by joesingo** [comment]
When implementing, check that DP group selection works properly for selecting non-FITS files.

**Comment by joesingo** [comment]
This was implemented in 2ce3b93151615078f241f79d6f71fd4abc140c6e. @zemogle It would be good to get your thoughts on the following points:

* 'Select all' now dutifully selects non-FITS files (e.g. timelapses, `astrosource` outputs...). There is now *no way to automatically select all FITS files*. However, I changed 'Select reduced' to only select files with 'fits' in the name but not ones that end with 'e00.fits.fz'. Maybe this is good enough?

* For creating timelapses, I added a simple check for whether 'fits' appears in the filename for each selected product. This is not foolproof, since i) non-FITS files might have 'fits' in the name (in which the timelapse fails with message 'An unexpected error occurred'), and ii) legit FITS files might not have 'fits' in their name. But again, maybe this is good enough?

* It is now possible to view the thumbnail gallery for non-FITS files. There is no thumbnail for such files, but they do appear in the gallery with checkboxes. Should this be allowed?

* Same issue as above with pipelines. Maybe the user-defined pipelines should be able to specify a file suffix for input files, and an error appears if trying to run the pipeline on files whose names do not mach?

**Comment by joesingo** [comment]
This is what the gallery look like when some data products don't have thumbnails..

![gallery](https://user-images.githubusercontent.com/12171762/62794001-e171c300-baca-11e9-8580-804bb4a79471.png)

**Comment by zemogle** [comment]
- Its not disastrous to have gallery items which can't generate thumbnails. The code should probably recognize when a thumbnail can't be created and show a placeholder icon. 

- `astrosource` can take a `format` input parameter which defaults to `.fz`. The files have to be either fits or text format for the code to parse them.

- The selectable file types could be applied only to the ones which are tagged 'Image'?. Having them only work on reduced types is a good start.

**Comment by joesingo** [comment]
> astrosource can take a format input parameter which defaults to .fz. The files have to be either fits or text format for the code to parse them.

Sounds good. There is already the `filetype` argument to `astrosource.gather_files()`, but currently this is hardcoded in `tom_astrosource`. Maybe I'll change it to read it from `settings.py`, and it can be `.fz` by default.

> The selectable file types could be applied only to the ones which are tagged 'Image'?. Having them only work on reduced types is a good start.

Do you mean to only show the checkboxes for ones tagged 'Image'? I thought the checkboxes for *all* products would be useful e.g. for selecting astrosource outputs to delete in batches (once I've done #20).

In any case, I'm pretty sure the `tom_base` code does not actually set a tag when saving LCO data products, which is a bit of a pain!

**Comment by zemogle** [comment]
Actually, I was talking about the `--format` input parameter:

https://github.com/zemogle/astrosource/blob/d02a9ae274cd88ca119f912433f078e19173abb5/astrosource/main.py#L37

The checkboxes should be there for all types, because it would be really useful to use it to delete multiple dataproducts.

Would it be worth overriding the `save()`/ingest for fits dataproducts in `tom_education` to add the Image tag?

**Comment by joesingo** [comment]
> Would it be worth overriding the save()/ingest for fits dataproducts in tom_education to add the Image tag?

I suppose that's possible in principle :) From a quick look through the code I'm not sure how to do it other than to look at the filename to check whether it ends with `.fz` or something, which is not ideal.

**Comment by joesingo** [comment]
But anyway I think I misunderstood your original point @zemogle. What would the 'Image' tag be used for in relation to the checkboxes?

**Comment by zemogle** [comment]
I meant in relation to knowing which files to apply the pipeline/timelapses to.

**Comment by joesingo** [comment]
@zemogle I've opted to change the `PipelineProcess` to allow sub-classes class to specify an `allowed_suffixes` list, e.g. for astosource it is
```python
class AstrosourceProcess(PipelineProcess):
    short_name = 'astrosource'
    allowed_suffixes = ['.fz', '.fits.fz', '.psx']
    ...
```

The job will fail and an appropriate error message shown if trying to run the pipeline with input files that match none of the suffixes. I've done the same thing for timelapses.
