### ISSUE TITLE
Add ability to hide raw unsaved data products in observation view

### ISSUE THREAD

**Issue by joesingo** [joesingo/tom_education#26]
In the observation view under 'Unsaved Data Products', add a checkbox 'Hide raw files' which is checked by default. When checked, raw files will be hidden from the table below. 

(Make sure the 'select all' etc does not select the hidden rows)

To determine whether a DP is raw or not, look at the `RLEVEL` field in the LCO API response.

**Comment by joesingo** [comment]
`RLEVEL` is 0 for raw, and 91 for reduced.

**Comment by joesingo** [comment]
@zemogle This is provisionally done, but not in the way described above. I have instead used the same buttons as on the target detail and gallery pages, namely 'select all', 'select reduced' and 'deselect all' to improve consistency. So instead of hiding the raw rows as you suggested, they appear in the table but can be ignored. Let me know what you reckon, since I know this is not what you asked for.

![screenshot](https://user-images.githubusercontent.com/12171762/62959561-0169f500-bdf1-11e9-964b-34ca3da79068.png)

(the screenshot is after having successfully saved only reduced files).

The reason for doing this was consistency between pages, and also to make it quicker to implement for now: I already have a template for the selection buttons, JS code for the selection etc..., and hiding the rows would require refactoring of the `tom_base` code to handle the 'Save All' button when rows are hidden. But the original idea of hiding rows is still possible if desired.

**Comment by zemogle** [comment]
I think that's fine.
