### ISSUE TITLE
Latest timelapse does not work for WebM/MP4 timelapses

### ISSUE THREAD

**Issue by joesingo** [joesingo/tom_education#45]
Currently [the template](https://github.com/joesingo/tom_education/blob/master/tom_education/templates/tom_dataproducts/partials/dataproduct_other_for_target.html#L7) uses an `<img>` tag which will only work for GIFs.

If this is fine, maybe the `dataproduct_other_for_target` tag should be changed to get only GIF timelapses to avoid the 'not found' placeholder you get when putting a WebM inside an `<img>`

**Comment by zemogle** [comment]
Should be working as of 665af6df2f1dccca8cdfa62c8bbe6dc01a21bb56
